/*

    @---------------------
    @ This module is indigenous to the rest of the system.
    @ Developed by the developer: dev.r1nex
    @----------------------

*/

// -- Vehicles Resources

#include "sources/systems/vehicles/resources.inc"

// -- Other Systems
#include "sources/systems/other/main.inc"

// -- Player Core
#include "sources/systems/player/resources.inc"
#include "sources/systems/player/main.inc"

// -- GreenZone System
#include "sources/systems/greenzone_system/resources.inc"
#include "sources/systems/greenzone_system/main.inc"

// -- Transport System
#include "sources/systems/transport_system/resources.inc"
#include "sources/systems/transport_system/main.inc"

// -- Admin Core
#include "sources/systems/admin_system/resources.inc"
#include "sources/systems/admin_system/main.inc"

// -- Vehicles Core
#include "sources/systems/vehicles/main.inc"

// -- Chat Core
#include "sources/systems/chat_system/main.inc"

// -- House System
#include "sources/systems/house_system/resources.inc"
#include "sources/systems/house_system/main.inc"

// -- PayDay System
#include "sources/systems/payday_system/main.inc"

// -- Rent System
#include "sources/systems/rent_system/resources.inc"
#include "sources/systems/rent_system/main.inc"

// -- Hud System
#include "sources/systems/hud_system/resources.inc"
#include "sources/systems/hud_system/main.inc"